### ISSUE TITLE
Time series analysis?

### ISSUE THREAD

**Issue by 1e100** [cjph8914/2020_benfords#28]
Via Twitter: someone on 4chan, of all places, scraped time series from NYT and analyzed GOP/Dem vote share drift in vote count deltas over time. That is, with each update, what's the percentage of the update for Biden vs Trump (or at least that's how I understand it). Outside the turbulent period where in-person votes are counted, mail-in tended to drift slightly towards GOP over time in uncontested areas (both GOP and Dem), which they explain away as rural votes taking longer to arrive, and steeply towards Dem in contested ones.

Given where this comes from, take it with a massive grain of salt - I can't vouch for veracity of the data. I'm attaching the CSV if anyone wants to verify/take a look.

[2020_election_time_series.zip](https://github.com/cjph8914/2020_benfords/files/5507997/2020_election_time_series.zip)

Not linking the Twitter thread here, as it launches into several conspiracies which we here can neither confirm nor deny.

**Comment by 1e100** [comment]
Correction - the "dem upward drift" is not observed in Arizona or Nevada, best I can tell. WI, PA, VA, GA, and MI show it quite clearly, however.

**Comment by 1e100** [comment]
Examples:

### GA
![pa](https://user-images.githubusercontent.com/38598618/98500533-954b8c00-2201-11eb-9f51-7492513f328e.png)


### AZ
![az](https://user-images.githubusercontent.com/38598618/98500538-9da3c700-2201-11eb-937d-2f04ecc22d1e.png)


### NV
![nv](https://user-images.githubusercontent.com/38598618/98500545-a4323e80-2201-11eb-873b-a507360ea7f0.png)


### PA
![pa](https://user-images.githubusercontent.com/38598618/98500554-aa281f80-2201-11eb-88b6-37bfe6d4cb9b.png)

**Comment by 1e100** [comment]
### FL
![fl](https://user-images.githubusercontent.com/38598618/98500691-fbd0aa00-2201-11eb-8a8b-21cec7b85eb8.png)

### WI (notice the "step" towards the end)
![wi](https://user-images.githubusercontent.com/38598618/98500705-04c17b80-2202-11eb-8595-e8754b63b9e0.png)

**Comment by charlesmartin14** [comment]
@1e100   I haven't dug into this data yet, but from the reporting I listened to, it appeared that kin the contested areas, the upwards dem drift was sometimes widely misbalanced towards Biden.  This seemed like a red flag, and perhaps close to an example of what Klimick calls extreme fraud.

https://www.pnas.org/content/109/41/16469

**Comment by 1e100** [comment]
I think it corresponds more to the phenomenon shown on Fig 6 in the paper you linked, that is, "not developing a plateau" of vote share for the winning candidate.

As an aside: Russia is such a great case study in election fraud. As a Russian-American, I can confirm there hasn't been a single non-falsified election in Russia since the 90s. In the 90s there was one, and then current president Yeltsin almost lost to a communist, so they brought in American consultants to "fix" the runoff. True story, read up on it. https://www.latimes.com/archives/la-xpm-1996-07-09-mn-22423-story.html. That "almost lost" election was the first and the last free and fair election in Russian history. Everyone knows it, and everyone enables it.

**Comment by testes-t** [comment]
The uptick was explained by postponed counting of mail-in ballots, which tended to favour Democrats.

Virginia had the same development.

**Comment by 1e100** [comment]
I think these are _all_ mail-in ballots after a certain point. My understanding is they counted most or all "day of" ballots first and then moved on to mail-in. I could be wrong though. Certainly something to look into. Especially hard breaks in the graphs where Biden gets what looks like improbable luck.

**Comment by charlesmartin14** [comment]
There may be insights here to look at:

https://www.ntd.com/statistical-anomalies-in-biden-votes-analyses-indicate_525974.html

**Comment by charlesmartin14** [comment]
@1e100 How many data points are in the time series?

**Comment by charlesmartin14** [comment]
And do we have data like this ?  Votes per batch number ?

![image](https://user-images.githubusercontent.com/498448/98696011-23ba2d80-2328-11eb-8ce7-5979e70b0747.png)

**Comment by charlesmartin14** [comment]
Here's a great plot from Wisconsin.  I don't have the raw data yet...do we ?

![image](https://user-images.githubusercontent.com/498448/98698178-9c21ee00-232a-11eb-981b-f89ee6c2ce87.png)
